In [3]:
import tensorflow as tf

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 1s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.19229612,  0.8984217 ,  0.46696502,  0.13696903, -0.17735423,
        -0.56762916,  0.37693217, -0.02851806, -0.21283123, -0.15335633]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.0716021 , 0.21311717, 0.13843285, 0.09952307, 0.07267999,
        0.04919496, 0.12651396, 0.08434389, 0.07014673, 0.07444526]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2903 - accuracy: 0.9153
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1389 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1053 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0861 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0737 - accuracy: 0.9768


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0737 - accuracy: 0.9780


[0.0736800953745842, 0.9779999852180481]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.31133094e-07, 2.03378397e-10, 1.35740083e-06, 1.17692534e-05,
        6.90778251e-12, 4.04894251e-08, 9.24747258e-13, 9.99980330e-01,
        2.28725440e-07, 6.00974226e-06],
       [9.94961979e-08, 4.79679438e-04, 9.99513388e-01, 5.99813166e-06,
        3.71747737e-11, 6.06206783e-08, 2.87077370e-07, 3.21787291e-10,
        4.22561129e-07, 1.07296076e-13],
       [7.76313186e-07, 9.97223496e-01, 9.68452950e-05, 9.58471264e-06,
        6.41545048e-05, 5.33132879e-06, 1.77729798e-05, 2.32776534e-03,
        2.53421138e-04, 8.94755487e-07],
       [9.99969840e-01, 5.31861881e-11, 1.64779976e-05, 1.01827291e-09,
        3.57513932e-06, 8.35629024e-08, 8.89131479e-06, 1.07066955e-06,
        3.42334139e-09, 4.75664095e-08],
       [6.61297781e-06, 1.15545449e-08, 3.00231768e-05, 5.65242608e-08,
        9.94526565e-01, 1.55371410e-07, 7.46795877e-06, 1.00433026e-04,
        2.26939460e-06, 5.32640144e-03]], dtype=float32)>