In [7]:
import numpy as np

In [25]:
a = np.arange(3).reshape(3, 1)

In [14]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.dtype.name

'int32'

In [26]:
[[1., 0., 0.],
[0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [27]:
1.

1.0

In [28]:
1

1

In [29]:
a = np.arange(10)**3

In [35]:
a[:6:2]=100

In [36]:
a

array([100,   1, 100,  27, 100, 125, 216, 343, 512, 729], dtype=int32)

In [47]:
import numpy as np
arr1 = np.array([[8, 16, 44],[22, 40, 16]])
for x in arr1:
    for y in x:
        print(y)

8
16
44
22
40
16


In [53]:
np.sort([5, 2,2,6, 2, 1,1])

array([1, 1, 2, 2, 2, 5, 6])

In [54]:
rng.integers(5, size=(2, 4))

NameError: name 'rng' is not defined

In [91]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
img = Image.open('mob.png')
numpydata = asarray(img)

# data
print(numpydata)


[[[  1  76 128]
  [  1  76 128]
  [  1  76 128]
  ...
  [206  18 105]
  [206  18 105]
  [206  18 105]]

 [[  1  76 128]
  [  1  76 128]
  [  1  76 128]
  ...
  [206  18 105]
  [206  18 105]
  [206  18 105]]

 [[  1  76 128]
  [  1  76 128]
  [  1  76 128]
  ...
  [206  18 105]
  [206  18 105]
  [206  18 105]]

 ...

 [[ 22  46 176]
  [ 22  46 175]
  [ 22  46 175]
  ...
  [ 21  45 175]
  [ 21  45 175]
  [ 21  45 175]]

 [[ 22  46 176]
  [ 22  46 175]
  [ 22  46 175]
  ...
  [ 21  45 175]
  [ 21  45 175]
  [ 21  45 175]]

 [[ 22  45 177]
  [ 22  45 176]
  [ 22  45 176]
  ...
  [ 21  44 176]
  [ 21  44 176]
  [ 21  44 176]]]


In [116]:
img.size

(805, 863)

In [108]:
numpydata

array([[[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [206,  18, 105],
        [206,  18, 105],
        [206,  18, 105]],

       [[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [206,  18, 105],
        [206,  18, 105],
        [206,  18, 105]],

       [[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [206,  18, 105],
        [206,  18, 105],
        [206,  18, 105]],

       ...,

       [[ 22,  46, 176],
        [ 22,  46, 175],
        [ 22,  46, 175],
        ...,
        [ 21,  45, 175],
        [ 21,  45, 175],
        [ 21,  45, 175]],

       [[ 22,  46, 176],
        [ 22,  46, 175],
        [ 22,  46, 175],
        ...,
        [ 21,  45, 175],
        [ 21,  45, 175],
        [ 21,  45, 175]],

       [[ 22,  45, 177],
        [ 22,  45, 176],
        [ 22,  45, 176],
        ...,
        [ 21,  44, 176],
        [ 21,  44, 176],
        [ 21,  44, 176]]

In [123]:
a=np.sort(numpydata)
a

array([[[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [ 18, 105, 206],
        [ 18, 105, 206],
        [ 18, 105, 206]],

       [[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [ 18, 105, 206],
        [ 18, 105, 206],
        [ 18, 105, 206]],

       [[  1,  76, 128],
        [  1,  76, 128],
        [  1,  76, 128],
        ...,
        [ 18, 105, 206],
        [ 18, 105, 206],
        [ 18, 105, 206]],

       ...,

       [[ 22,  46, 176],
        [ 22,  46, 175],
        [ 22,  46, 175],
        ...,
        [ 21,  45, 175],
        [ 21,  45, 175],
        [ 21,  45, 175]],

       [[ 22,  46, 176],
        [ 22,  46, 175],
        [ 22,  46, 175],
        ...,
        [ 21,  45, 175],
        [ 21,  45, 175],
        [ 21,  45, 175]],

       [[ 22,  45, 177],
        [ 22,  45, 176],
        [ 22,  45, 176],
        ...,
        [ 21,  44, 176],
        [ 21,  44, 176],
        [ 21,  44, 176]]

In [124]:
a=a[:400,:400]

In [163]:
from PIL import Image
newimage = Image.new('RGB', (len(a[0]), len(a)))  # type, size
newimage.putdata([tuple(p) for row in a for p in row])
newimage.save("filename1.png")  # takes type from filename extension

In [167]:
a.shape

(400, 400, 3)

In [181]:
np.linspace(0,6,5 )

array([0. , 1.5, 3. , 4.5, 6. ])

In [184]:
6/4*4

6.0

In [172]:
a = 2
b=3
c = a+b

In [173]:
c

5

In [174]:
print('welcome')

welcome


In [176]:
e = np.arange(100).reshape(10,10)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
e[2:8,2:8]

array([[22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77]])