### reinforcement Learning
1. initial testing 

In [3]:
import gym   # importing the dependancy 
env = gym.make('CartPole-v0') # Carpole -v0 model of the inverted pandulem from the gym lib
states = env.observation_space.shape[0]
actions = env.action_space.n

C:\Users\Hisham Khalil\anaconda3\lib\site-packages\gym\envs\registration.py:505: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1` with the environment ID `CartPole-v1`.
  logger.warn(


In [4]:
for i_episode in range(100): # appling for loop for the 20 obsevation 
    observation = env.reset() # initially making reset the envirment wherein the carpole has to move 
    for t in range(100): # passing a though the for loop wherein the range i
        env.render() # appling rendering  
        print(observation) 
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            #print('Episode:{} Score:{}'.format(episode, score))
            break
env.close()

[ 0.03529366  0.00930189  0.03216657 -0.00280388]
[ 0.0354797   0.20394811  0.03211049 -0.28516683]
[ 0.03955866  0.39859775  0.02640715 -0.5675519 ]
[ 0.04753061  0.5933395   0.01505611 -0.8517999 ]
[ 0.0593974   0.39801556 -0.00197988 -0.5544209 ]
[ 0.06735772  0.5931653  -0.0130683  -0.84772694]
[ 0.07922102  0.788463   -0.03002284 -1.1444905 ]
[ 0.09499028  0.5937458  -0.05291265 -0.86137176]
[ 0.1068652   0.39938283 -0.07014009 -0.5857843 ]
[ 0.11485285  0.59541345 -0.08185577 -0.8997116 ]
[ 0.12676112  0.4014905  -0.09985001 -0.63383985]
[ 0.13479093  0.20789275 -0.1125268  -0.37419677]
[ 0.13894878  0.40441826 -0.12001073 -0.70013374]
[ 0.14703715  0.6009814  -0.13401341 -1.0280564 ]
[ 0.15905678  0.7976078  -0.15457454 -1.3596334 ]
[ 0.17500894  0.6047244  -0.18176721 -1.1190221 ]
[ 0.18710342  0.8017043  -0.20414765 -1.4627701 ]
Episode finished after 17 timesteps
[ 0.01587595 -0.04731378  0.03400929 -0.02313347]
[ 0.01492967 -0.24290653  0.03354662  0.28008282]
[ 0.01007154 -

[ 0.01239759 -0.03808055  0.01662974  0.03130906]
[ 0.01163598  0.15679903  0.01725592 -0.25608096]
[ 0.01477196  0.3516704   0.0121343  -0.54327154]
[ 0.02180537  0.15638006  0.00126887 -0.24679016]
[ 0.02493297 -0.03876    -0.00366693  0.04629273]
[ 0.02415777 -0.23382919 -0.00274108  0.33781645]
[ 0.01948119 -0.03866833  0.00401525  0.0442704 ]
[ 0.01870782  0.15639582  0.00490066 -0.24714297]
[ 2.1835739e-02 -3.8795780e-02 -4.2198750e-05  4.7081698e-02]
[ 0.02105982  0.15632677  0.00089944 -0.24561454]
[ 0.02418636  0.35143587 -0.00401286 -0.53801364]
[ 0.03121508  0.15637057 -0.01477313 -0.24659781]
[ 0.03434249 -0.03853732 -0.01970509  0.04138897]
[ 0.03357174  0.15686157 -0.01887731 -0.2574454 ]
[ 0.03670897 -0.03798585 -0.02402621  0.02922408]
[ 0.03594926 -0.23275515 -0.02344173  0.31423068]
[ 0.03129415 -0.03730725 -0.01715712  0.01424815]
[ 0.03054801  0.1580565  -0.01687215 -0.28379828]
[ 0.03370914 -0.0368208  -0.02254812  0.00351586]
[ 0.03297272 -0.23161224 -0.0224778   

[-0.12369749 -0.41026342  0.07635633  0.48919126]
[-0.13190275 -0.21629706  0.08614016  0.22151642]
[-0.1362287  -0.41253787  0.09057049  0.54008013]
[-0.14447945 -0.60880846  0.10137209  0.8598706 ]
[-0.15665562 -0.80515414  0.1185695   1.1826296 ]
[-0.17275871 -1.0015981   0.14222209  1.5100044 ]
[-0.19279067 -1.1981281   0.17242219  1.8434955 ]
[-0.21675323 -1.3946819   0.20929208  2.1843958 ]
Episode finished after 28 timesteps
[ 0.01581143 -0.02556651  0.01229208  0.04679561]
[ 0.0153001  -0.22086255  0.01322799  0.3433313 ]
[ 0.01088285 -0.02593126  0.02009462  0.05484888]
[ 0.01036423 -0.22133549  0.02119159  0.35380346]
[ 0.00593752 -0.41675225  0.02826766  0.6530927 ]
[-0.00239753 -0.6122562   0.04132951  0.954541  ]
[-0.01464265 -0.41771388  0.06042033  0.6751241 ]
[-0.02299693 -0.6136211   0.07392282  0.9862015 ]
[-0.03526935 -0.8096511   0.09364685  1.3011569 ]
[-0.05146237 -0.6158339   0.11966999  1.039197  ]
[-0.06377905 -0.42248765  0.14045392  0.7863509 ]
[-0.0722288  -

[ 0.16300242  0.7292962  -0.04487331 -0.63085383]
[ 0.17758834  0.9250146  -0.05749039 -0.9373242 ]
[ 0.19608864  0.730713   -0.07623687 -0.6632462 ]
[ 0.2107029   0.9268082  -0.0895018  -0.97892654]
[ 0.22923906  0.7329927  -0.10908033 -0.7156454 ]
[ 0.24389891  0.9294419  -0.12339324 -1.0405738 ]
[ 0.26248777  1.1259677  -0.14420472 -1.3693068 ]
[ 0.28500712  1.3225693  -0.17159085 -1.7033976 ]
[ 0.3114585   1.129788   -0.20565881 -1.468673  ]
Episode finished after 49 timesteps
[ 0.0119015  -0.01486827  0.03979146  0.00161765]
[ 0.01160414  0.1796611   0.03982382 -0.2782498 ]
[ 0.01519736 -0.01600568  0.03425882  0.02672276]
[ 0.01487725 -0.21160176  0.03479327  0.33001482]
[ 0.01064521 -0.4072013   0.04139357  0.6334637 ]
[ 0.00250119 -0.6028755   0.05406284  0.9388898 ]
[-0.00955632 -0.7986829   0.07284064  1.2480587 ]
[-0.02552998 -0.9946593   0.09780181  1.5626398 ]
[-0.04542317 -1.1908054   0.1290546   1.8841611 ]
[-0.06923928 -1.3870742   0.16673782  2.2139528 ]
Episode finish

[-0.03668518  0.34738323 -0.03363642 -0.5996374 ]
[-0.02973752  0.15274763 -0.04562917 -0.31773636]
[-0.02668256  0.34848878 -0.05198389 -0.62445277]
[-0.01971279  0.54429644 -0.06447295 -0.93304396]
[-0.00882686  0.35010085 -0.08313383 -0.6612977 ]
[-0.00182484  0.54627514 -0.09635978 -0.97895604]
[ 0.00910066  0.74254763 -0.1159389  -1.300285  ]
[ 0.02395161  0.9389343  -0.1419446  -1.6268971 ]
[ 0.0427303   0.74573845 -0.17448254 -1.3816096 ]
[ 0.05764507  0.5531697  -0.20211473 -1.1481802 ]
Episode finished after 12 timesteps
[ 0.01367077  0.00178902 -0.00186488 -0.03244891]
[ 0.01370655  0.19693767 -0.00251386 -0.32571965]
[ 0.01764531  0.39209533 -0.00902826 -0.61919427]
[ 0.02548721  0.19710062 -0.02141214 -0.3293684 ]
[ 0.02942923  0.00228993 -0.02799951 -0.04351405]
[ 0.02947502 -0.19241956 -0.02886979  0.24020493]
[ 0.02562663 -0.38711748 -0.02406569  0.52364355]
[ 0.01788428 -0.5818926  -0.01359282  0.80864704]
[ 0.00624643 -0.38658705  0.00258012  0.5117196 ]
[-0.00148531 -

[-0.02369446 -0.40491664  0.04499929  0.66005516]
[-0.03179279 -0.600635    0.0582004   0.96656084]
[-0.04380549 -0.7964882   0.07753161  1.2769445 ]
[-0.05973526 -0.6024357   0.1030705   1.0095116 ]
[-0.07178397 -0.40882915  0.12326074  0.75089216]
[-0.07996055 -0.6054159   0.13827857  1.079682  ]
[-0.09206887 -0.4123635   0.15987222  0.83339196]
[-0.10031614 -0.2197448   0.17654006  0.59495085]
[-0.10471104 -0.41684085  0.18843907  0.9376334 ]
[-0.11304785 -0.22469056  0.20719175  0.709584  ]
Episode finished after 16 timesteps
[ 0.04343883  0.02396812  0.00967001 -0.02321838]
[ 0.04391819  0.21895008  0.00920564 -0.31283468]
[ 0.04829719  0.0236982   0.00294895 -0.01726287]
[ 0.04877115 -0.17146592  0.00260369  0.27634904]
[ 0.04534183  0.02361879  0.00813067 -0.01551156]
[ 0.04581421  0.21862319  0.00782044 -0.3056181 ]
[ 0.05018668  0.02339068  0.00170808 -0.01047911]
[ 0.05065449  0.2184881   0.0014985  -0.30262262]
[ 0.05502425  0.02334481 -0.00455396 -0.00946748]
[ 0.05549115 -

[-0.26150253 -0.36030608 -0.03083676 -0.23489006]
[-0.26870865 -0.16475743 -0.03553456 -0.53713816]
[-0.2720038   0.03084565 -0.04627732 -0.8408025 ]
[-0.2713869   0.22656779 -0.06309337 -1.147672  ]
[-0.26685554  0.42245418 -0.08604681 -1.4594542 ]
[-0.25840646  0.61851954 -0.11523589 -1.7777307 ]
[-0.24603605  0.81473523 -0.15079051 -2.1039066 ]
[-0.22974135  1.0110143  -0.19286864 -2.439149  ]
Episode finished after 50 timesteps
[ 0.01122888 -0.00186034  0.0082276  -0.00036331]
[ 0.01119168 -0.19709931  0.00822033  0.29490414]
[ 0.00724969 -0.00209552  0.01411842  0.00482507]
[ 0.00720778 -0.19741707  0.01421492  0.30192888]
[ 0.00325944 -0.00250057  0.02025349  0.01376271]
[ 0.00320943 -0.19790705  0.02052875  0.31276643]
[-0.00074871 -0.00308347  0.02678408  0.02662766]
[-0.00081038 -0.19857907  0.02731663  0.3276395 ]
[-0.00478196 -0.00385646  0.03386942  0.04369462]
[-0.00485909 -0.1994473   0.03474331  0.34686834]
[-0.00884804 -0.3950458   0.04168068  0.65030146]
[-0.01674895 -

[-0.1265617  -0.9995949   0.09879661  1.4377992 ]
[-0.1465536 -1.195786   0.1275526  1.7596496]
[-0.17046933 -1.0023184   0.1627456   1.5092046 ]
[-0.1905157  -1.1989955   0.19292969  1.8479582 ]
Episode finished after 13 timesteps
[-0.0496014   0.01740951 -0.04088521 -0.00964387]
[-0.04925321  0.21309324 -0.04107808 -0.31494108]
[-0.04499134  0.01857978 -0.0473769  -0.03549057]
[-0.04461975 -0.17583188 -0.04808672  0.24187613]
[-0.04813638  0.01994279 -0.04324919 -0.06557849]
[-0.04773753  0.21565728 -0.04456076 -0.371587  ]
[-0.04342438  0.02119578 -0.05199251 -0.09328084]
[-0.04300047  0.2170229  -0.05385812 -0.40190348]
[-0.03866001  0.02270457 -0.06189619 -0.12667528]
[-0.03820592 -0.17147857 -0.06442969  0.14585578]
[-0.04163549 -0.3656215  -0.06151258  0.41753674]
[-0.04894792 -0.55982023 -0.05316184  0.69021064]
[-0.06014432 -0.75416577 -0.03935763  0.96569484]
[-0.07522764 -0.5585379  -0.02004374  0.66091216]
[-0.0863984  -0.36314288 -0.00682549  0.36198598]
[-9.3661256e-02 -5

[ 0.0890904   0.9885775  -0.08668423 -1.4836671 ]
[ 0.10886195  0.79461294 -0.11635757 -1.2192659 ]
[ 0.12475421  0.9910265  -0.1407429  -1.5460261 ]
[ 0.14457473  1.1875303  -0.17166342 -1.8791093 ]
[ 0.16832535  0.99464554 -0.2092456  -1.6442561 ]
Episode finished after 14 timesteps
[-0.01884299  0.04744661  0.00815142  0.02822117]
[-0.01789406  0.24245073  0.00871584 -0.2618788 ]
[-0.01304504  0.4374472   0.00347826 -0.55179995]
[-0.0042961   0.24227655 -0.00755773 -0.25802317]
[ 5.4943125e-04  4.3750557e-01 -1.2718197e-02 -5.5308032e-01]
[ 0.00929954  0.24256453 -0.0237798  -0.2644314 ]
[ 0.01415083  0.43801767 -0.02906843 -0.56451887]
[ 0.02291119  0.24331537 -0.04035881 -0.28113368]
[ 0.02777749  0.43898907 -0.04598148 -0.58626753]
[ 0.03655728  0.24454029 -0.05770683 -0.3084164 ]
[ 0.04144808  0.44043496 -0.06387516 -0.6187257 ]
[ 0.05025678  0.63638824 -0.07624967 -0.93082273]
[ 0.06298455  0.44237357 -0.09486613 -0.663042  ]
[ 0.07183202  0.6386784  -0.10812697 -0.98402405]
[ 

[ 0.06237525  0.5569484  -0.10785937 -1.0831745 ]
[ 0.07351422  0.7533155  -0.12952286 -1.4076626 ]
[ 0.08858053  0.9497848  -0.15767612 -1.7378714 ]
[ 0.10757622  1.1463135  -0.19243354 -2.0751724 ]
Episode finished after 21 timesteps
[ 0.02407108 -0.03877628  0.02680315  0.02037587]
[ 0.02329555 -0.23427217  0.02721066  0.32139355]
[ 0.01861011 -0.03954806  0.03363853  0.03741447]
[ 0.01781915  0.15507576  0.03438682 -0.24446826]
[ 0.02092066  0.3496901   0.02949746 -0.52610946]
[ 0.02791446  0.15416579  0.01897527 -0.22427957]
[ 0.03099778 -0.04122216  0.01448968  0.07432798]
[ 0.03017334  0.1536891   0.01597624 -0.21374841]
[ 0.03324712  0.34857905  0.01170127 -0.5013492 ]
[ 0.0402187   0.15329412  0.00167429 -0.20500177]
[ 0.04328458  0.3483921  -0.00242575 -0.49715608]
[ 0.05025242  0.54354817 -0.01236887 -0.7906025 ]
[ 0.06112339  0.3485982  -0.02818092 -0.5018363 ]
[ 0.06809535  0.1538846  -0.03821765 -0.21816593]
[ 0.07117304  0.34953144 -0.04258097 -0.5226551 ]
[ 0.07816367  

[-0.04497554 -0.01230153  0.01743477  0.05309175]
[-0.04522157  0.18256615  0.01849661 -0.23403977]
[-0.04157025  0.377419    0.01381581 -0.52083135]
[-0.03402187  0.18210532  0.00339919 -0.22382708]
[-0.03037976 -0.01306505 -0.00107736  0.06992614]
[-3.0641066e-02 -2.0817153e-01  3.2116775e-04  3.6226895e-01]
[-0.0348045  -0.40329805  0.00756655  0.65505314]
[-0.04287046 -0.5985245   0.02066761  0.950109  ]
[-0.05484095 -0.4036868   0.03966979  0.6639907 ]
[-0.06291468 -0.59933746  0.0529496   0.9688957 ]
[-0.07490143 -0.40496486  0.07232752  0.69330525]
[-0.08300073 -0.21091683  0.08619362  0.42424   ]
[-0.08721907 -0.4071473   0.09467842  0.7428025 ]
[-0.09536202 -0.21345085  0.10953447  0.48135298]
[-0.09963103 -0.02003165  0.11916153  0.2251017 ]
[-0.10003166  0.17320354  0.12366357 -0.027745  ]
[-0.09656759 -0.02345488  0.12310866  0.3012544 ]
[-0.09703669 -0.22009677  0.12913376  0.63008744]
[-0.10143863 -0.41676164  0.14173551  0.9604885 ]
[-0.10977386 -0.61347485  0.16094527  

[ 0.01244934  0.16427538 -0.02954183 -0.29303196]
[ 0.01573485  0.3598058  -0.03540247 -0.5948837 ]
[ 0.02293096  0.5554049  -0.04730014 -0.8985046 ]
[ 0.03403906  0.75113493 -0.06527023 -1.2056724 ]
[ 0.04906176  0.9470368  -0.08938368 -1.5180753 ]
[ 0.0680025   1.1431189  -0.11974518 -1.837268  ]
[ 0.09086487  1.3393434  -0.15649055 -2.1646183 ]
[ 0.11765175  1.1460603  -0.19978291 -1.9240571 ]
Episode finished after 9 timesteps
[ 0.01868898  0.03676312 -0.00149118 -0.02367751]
[ 0.01942424  0.23190643 -0.00196473 -0.31683055]
[ 0.02406237  0.03681251 -0.00830134 -0.02476788]
[ 0.02479862  0.23205252 -0.0087967  -0.32005838]
[ 0.02943967  0.42729864 -0.01519786 -0.6155024 ]
[ 0.03798565  0.2323923  -0.02750791 -0.32764465]
[ 0.04263349  0.03767255 -0.0340608  -0.04376183]
[ 0.04338694 -0.15694486 -0.03493604  0.237983  ]
[ 0.04024805  0.03865834 -0.03017638 -0.06551185]
[ 0.04102121 -0.15601826 -0.03148662  0.2174996 ]
[ 0.03790085  0.03953932 -0.02713663 -0.08494692]
[ 0.03869164  0

[-0.01531051  0.05574154 -0.06365786 -0.342022  ]
[-0.01419567  0.2517087  -0.0704983  -0.6540801 ]
[-0.0091615   0.0576355  -0.0835799  -0.38440275]
[-0.00800879  0.25383845 -0.09126795 -0.7022237 ]
[-0.00293202  0.45009893 -0.10531243 -1.0221847 ]
[ 0.00606996  0.64645416 -0.12575611 -1.3459904 ]
[ 0.01899904  0.45311764 -0.15267593 -1.0951507 ]
[ 0.02806139  0.64988434 -0.17457895 -1.4315801 ]
[ 0.04105908  0.8466777  -0.20321055 -1.773349  ]
Episode finished after 25 timesteps
[ 0.02447645  0.03835065  0.04257096 -0.04950414]
[ 0.02524346  0.23283713  0.04158087 -0.32845747]
[ 0.02990021  0.03714865  0.03501172 -0.02295722]
[ 0.03064318 -0.15845744  0.03455258  0.28056347]
[ 0.02747403  0.03615502  0.04016385 -0.00102457]
[ 0.02819713  0.23067863  0.04014336 -0.28076968]
[0.0328107  0.03500773 0.03452796 0.02429919]
[ 0.03351086 -0.16059193  0.03501395  0.32767302]
[ 0.03029902 -0.3561944   0.04156741  0.6311889 ]
[ 0.02317513 -0.55187094  0.05419118  0.93666744]
[ 0.01213771 -0.35

[ 0.03390035  0.4029757  -0.03203084 -0.5864959 ]
[ 0.04195987  0.5985313  -0.04376076 -0.88909423]
[ 0.05393049  0.7942189  -0.06154264 -1.1952062 ]
[ 0.06981488  0.9900813  -0.08544677 -1.5065258 ]
[ 0.0896165   0.7960932  -0.11557728 -1.241696  ]
[ 0.10553836  0.99249345 -0.1404112  -1.568235  ]
[ 0.12538823  0.7992999  -0.1717759  -1.322442  ]
[ 0.14137423  0.99612474 -0.19822474 -1.6635884 ]
Episode finished after 10 timesteps
[-0.04074727  0.04100448 -0.02968199 -0.02714694]
[-0.03992718 -0.15367952 -0.03022493  0.2560252 ]
[-0.04300077 -0.3483572  -0.02510443  0.5390235 ]
[-0.04996791 -0.15289147 -0.01432396  0.23853745]
[-0.05302574  0.04243214 -0.00955321 -0.05862904]
[-0.0521771   0.23768976 -0.01072579 -0.3543107 ]
[-0.04742331  0.43296257 -0.017812   -0.65035635]
[-0.03876406  0.23809318 -0.03081913 -0.36333513]
[-0.03400219  0.0434225  -0.03808583 -0.08052715]
[-0.03313374 -0.15113337 -0.03969638  0.1999005 ]
[-0.03615641  0.04453319 -0.03569837 -0.1050358 ]
[-0.03526574  

### importing lib from keras 
1. keras 
2. sequential 
3. dense layer 
4. flatten layer 
5. optimizer 

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

### defining function of model 
1. adding layer 
2. sequentail 
3. dense 24
4. falttern 

In [ ]:
def build_model(states, actions):
    model = Sequential()
    model.add(Flatten(input_shape=(1,states)))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(actions, activation='linear'))
    return model

In [ ]:
model = build_model(states, actions)
model

In [ ]:
model.summary()

### building an agent for reinforcement of the test model wherein the initial data is considered 

In [ ]:
from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

In [ ]:
def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, memory=memory, policy=policy, 
                  nb_actions=actions, nb_steps_warmup=10, target_model_update=1e-2)
    return dqn

In [ ]:
dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
dqn.fit(env, nb_steps=500, visualize=False, verbose=1)

In [ ]:
scores = dqn.test(env, nb_episodes=100, visualize=False)
print(np.mean(scores.history['episode_reward']))

In [ ]:
dqn.save_weights('dqn_weights.h5f', overwrite=True)

In [ ]:
del model
del dqn
del env

In [ ]:
env = gym.make('CartPole-v0')
actions = env.action_space.n
states = env.observation_space.shape[0]
model = build_model(states, actions)
dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
env.close()

In [ ]:
dqn.load_weights('dqn_weights.h5f')

In [ ]:
_ = dqn.test(env, nb_episodes=100, visualize=True)